; DefaultDeviceProfiles.ini

[Windows DeviceProfile]
BaseProfileName=
+CVars=r.DynamicGlobalIlluminationMethod=0

[Windows_Low DeviceProfile]
BaseProfileName=Windows
+CVars=r.DynamicGlobalIlluminationMethod=0

[Windows_High DeviceProfile]
BaseProfileName=Windows
+CVars=r.DynamicGlobalIlluminationMethod=1
